name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: |
          mkdir -p build
          go build -o build/certstream-scout ./cmd/worker

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: certstream-scout
          path: build/certstream-scout
