name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binaries for multiple platforms
        run: |
          platforms=("linux/amd64" "darwin/amd64" "darwin/arm64" "windows/amd64")
          
          for platform in "${platforms[@]}"; do
            IFS="/" read -r os arch <<< "$platform"
            
            if [ "$os" == "windows" ]; then
              binary_name="certstream-scout-${os}-${arch}.exe"
            elif [ "$os" == "darwin" ]; then
              binary_name="certstream-scout-macOS-${arch}"
            else
              binary_name="certstream-scout-${os}-${arch}"
            fi
            
            # Build the binary for the platform
            GOOS=$os GOARCH=$arch go build -o build/$binary_name ./certstream-scout.go
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
